#!/bin/bash
source ../../versions

rm -rf sf
mkdir sf

OS_full=opensuse-leap-15.1
OS=suse.lp151

URL=https://downloads.sourceforge.net/project/intel-compute-runtime/${neo_ver}/${OS_full}

for p in libigdgmm11-${gmm_ver}-1 libigdgmm11-devel-${gmm_ver}-1 \
    intel-igc-core-${igc_ver}-1 intel-igc-opencl-${igc_ver}-1 intel-igc-opencl-devel-${igc_ver}-1 \
    intel-opencl-${neo_ver}-2
do
    f=${p}.${OS}.x86_64.rpm
    wget -O sf/$f ${URL}/$f
done

