#!/bin/bash

. ./version
. ../../../versions

git clone -b release/10.x --depth 200 https://github.com/llvm/llvm-project
cd llvm-project
git reset --hard ${llvm_commit}
cd ..
tar czf intel-graphics-compiler_${igc_ver}.orig-llvm-project.tar.gz llvm-project
rm -rf llvm-project

git clone -b ocl-open-100 https://github.com/intel/opencl-clang
cd opencl-clang
git reset --hard ${opencl_clang_commit}
cd ..
tar czf intel-graphics-compiler_${igc_ver}.orig-opencl-clang.tar.gz opencl-clang
rm -rf opencl-clang

wget --no-check-certificate https://github.com/intel/vc-intrinsics/archive/${vc_intrinsics_commit}/intel-graphics-compiler_${igc_ver}.orig-vc-intrinsics.tar.gz

git clone -b llvm_release_100 https://github.com/KhronosGroup/SPIRV-LLVM-Translator
cd SPIRV-LLVM-Translator
git reset --hard ${spirv_llvm_translator_commit}
cd ..
tar czf intel-graphics-compiler_${igc_ver}.orig-llvm-spirv.tar.gz SPIRV-LLVM-Translator
rm -rf SPIRV-LLVM-Translator

wget --no-check-certificate https://github.com/intel/intel-graphics-compiler/archive/${igc_commit}/intel-graphics-compiler_${igc_ver}.orig-igc.tar.gz

scp intel-graphics-compiler_${igc_ver}.orig-llvm-project.tar.gz mirror:/tmp
scp intel-graphics-compiler_${igc_ver}.orig-opencl-clang.tar.gz mirror:/tmp
scp intel-graphics-compiler_${igc_ver}.orig-llvm-spirv.tar.gz mirror:/tmp
scp intel-graphics-compiler_${igc_ver}.orig-igc.tar.gz mirror:/tmp
scp intel-graphics-compiler_${igc_ver}.orig-vc-intrinsics.tar.gz mirror:/tmp

