#!/bin/bash

. ./version
. ../../../versions

wget --no-check-certificate https://github.com/llvm/llvm-project/archive/${llvm_commit}/intel-graphics-compiler_${igc_ver}.orig-llvm-project.tar.gz
wget --no-check-certificate https://github.com/intel/opencl-clang/archive/${opencl_clang_commit}/intel-graphics-compiler_${igc_ver}.orig-opencl-clang.tar.gz
wget --no-check-certificate https://github.com/intel/vc-intrinsics/archive/${vc_intrinsics_commit}/intel-graphics-compiler_${igc_ver}.orig-vc-intrinsics.tar.gz

git clone -b llvm_release_100 https://github.com/KhronosGroup/SPIRV-LLVM-Translator
cd SPIRV-LLVM-Translator
git checkout -b open-clang ${spirv_llvm_translator_commit}
cd ..
tar czf intel-graphics-compiler_${igc_ver}.orig-llvm-spirv.tar.gz SPIRV-LLVM-Translator
rm -rf SPIRV-LLVM-Translator

wget --no-check-certificate https://github.com/intel/llvm-patches/archive/${llvm_patches_commit}/intel-graphics-compiler_${igc_ver}.orig-llvm-patches.tar.gz
wget --no-check-certificate https://github.com/intel/intel-graphics-compiler/archive/${igc_commit}/intel-graphics-compiler_${igc_ver}.orig-igc.tar.gz

scp intel-graphics-compiler_${igc_ver}.orig-llvm-project.tar.gz mirror:/tmp
scp intel-graphics-compiler_${igc_ver}.orig-opencl-clang.tar.gz mirror:/tmp
scp intel-graphics-compiler_${igc_ver}.orig-llvm-spirv.tar.gz mirror:/tmp
scp intel-graphics-compiler_${igc_ver}.orig-llvm-patches.tar.gz mirror:/tmp
scp intel-graphics-compiler_${igc_ver}.orig-igc.tar.gz mirror:/tmp
scp intel-graphics-compiler_${igc_ver}.orig-vc-intrinsics.tar.gz mirror:/tmp

