#!/bin/bash

. ./version
. ../../../versions

rm -f intel-graphics-compiler_*.tar.gz
for f in llvm-project opencl-clang llvm-spirv llvm-patches igc 
do
	scp mirror:/tmp/intel-graphics-compiler_${igc_ver}.orig-${f}.tar.gz .
done

