#!/bin/bash

. ./version

rm -f intel-opencl_${VER}.orig.tar.gz
wget --no-check-certificate https://github.com/intel/compute-runtime/archive/${neo_commit_id}/intel-opencl_${VER}.orig.tar.gz
rm intel-opencl.tar.gz
ln -s intel-opencl_${VER}.orig.tar.gz intel-opencl.tar.gz

