#!/bin/bash
set -x

source `git rev-parse --show-toplevel`/versions

release=$(awk -F '=' '/^NEO_DRIVER_VERSION/ {print $2}' debian/rules)
echo "current neo: ${release}"

new_build=$(echo ${neo_ver} | awk -F '.' '{print $3}')
echo "new build: ${new_build}"


sed -i "s/^NEO_DRIVER_VERSION=${release}/NEO_DRIVER_VERSION=${neo_ver}/" debian/rules

