#!/bin/bash
source ../../../versions

wget https://launchpad.net/~ocl-dev/+archive/ubuntu/intel-opencl/+files/intel-gmmlib_${gmm_ver}-1~ppa1~bionic1_amd64.deb
wget https://launchpad.net/~ocl-dev/+archive/ubuntu/intel-opencl/+files/intel-gmmlib-dev_${gmm_ver}-1~ppa1~bionic1_amd64.deb
wget https://launchpad.net/~ocl-dev/+archive/ubuntu/intel-opencl/+files/libigc-dev_${igc_ver}-1~ppa1~bionic1_amd64.deb
wget https://launchpad.net/~ocl-dev/+archive/ubuntu/intel-opencl/+files/libigc_${igc_ver}-1~ppa1~bionic1_amd64.deb

