#!/bin/bash

. ./version

rm -f intel-gmmlib_${VER}.orig.tar.gz
wget --no-check-certificate https://github.com/intel/gmmlib/archive/${gmmlib_commit_id}/intel-gmmlib_${VER}.orig.tar.gz
rm gmmlib.tar.gz
ln -s intel-gmmlib_${VER}.orig.tar.gz gmmlib.tar.gz

