#!/bin/bash
source builds
source ../../versions

wget https://copr-be.cloud.fedoraproject.org/results/jdanecki/intel-opencl-ci/opensuse-leap-15.2-x86_64/${gmm_build}-intel-gmmlib/intel-gmmlib-${gmm_ver}-1.suse.lp152.x86_64.rpm
wget https://copr-be.cloud.fedoraproject.org/results/jdanecki/intel-opencl-ci/opensuse-leap-15.2-x86_64/${gmm_build}-intel-gmmlib/intel-gmmlib-devel-${gmm_ver}-1.suse.lp152.x86_64.rpm

wget https://copr-be.cloud.fedoraproject.org/results/jdanecki/intel-opencl-ci/opensuse-leap-15.2-x86_64/${igc_build}-intel-igc/intel-igc-core-${igc_ver}-1.suse.lp152.x86_64.rpm
wget https://copr-be.cloud.fedoraproject.org/results/jdanecki/intel-opencl-ci/opensuse-leap-15.2-x86_64/${igc_build}-intel-igc/intel-igc-opencl-${igc_ver}-1.suse.lp152.x86_64.rpm
wget https://copr-be.cloud.fedoraproject.org/results/jdanecki/intel-opencl-ci/opensuse-leap-15.2-x86_64/${igc_build}-intel-igc/intel-igc-opencl-devel-${igc_ver}-1.suse.lp152.x86_64.rpm


