#!/bin/bash
source ../../versions

echo "Disco is EOL"

#wget https://launchpad.net/~jdanecki/+archive/ubuntu/intel-opencl/+files/libigdgmm11_${gmm_ver}-1~ppa1~disco1_amd64.deb
#wget https://launchpad.net/~jdanecki/+archive/ubuntu/intel-opencl/+files/libigdgmm-dev_${gmm_ver}-1~ppa1~disco1_amd64.deb
#wget https://launchpad.net/~jdanecki/+archive/ubuntu/intel-opencl/+files/libigc-dev_${igc_ver}-1~ppa1~disco1_amd64.deb
#wget https://launchpad.net/~jdanecki/+archive/ubuntu/intel-opencl/+files/libigc_${igc_ver}-1~ppa1~disco1_amd64.deb
#wget https://launchpad.net/~jdanecki/+archive/ubuntu/intel-opencl/+files/intel-opencl-icd_${neo_ver}-1~ppa1~disco1_amd64.deb


