#!/bin/bash

source ../versions

#opensuse-tumbleweed

for d in centos-7 centos-8 centos-stream mageia-7 mageia-8 mageia-cauldron opensuse-leap-15.2  fedora-33 fedora-34 fedora-35 
do
	pushd $d
	./get
	popd
done


