#!/bin/bash

source ../versions

# ubuntu-18.04/ppa ubuntu-19.10 ubuntu-20.04 fedora-32 fedora-33

for d in centos-7 centos-8 fedora-30 fedora-31 mageia-7 opensuse-leap-15.1 opensuse-tumbleweed ubuntu-18.04 
do
	pushd $d
	./get-sf
	popd
done


