#!/bin/bash

source ../versions

#fedora-32 

for d in centos-7 centos-8 fedora-30 fedora-31 mageia-7 opensuse-leap-15.1 opensuse-tumbleweed
do
    rsync -av -e ssh $d ${USER}@frs.sourceforge.net:/home/frs/project/intel-compute-runtime/${neo_ver}/
done


