#!/bin/bash

source ../versions


for d in centos-7 centos-8 centos-stream mageia-7 opensuse-leap-15.2 opensuse-tumbleweed fedora-32 fedora-33 fedora-34 fedora-35
do
    rsync -av -e ssh $d ${USER}@frs.sourceforge.net:/home/frs/project/intel-compute-runtime/${neo_ver}/
done


