#!/bin/bash
set -x

source `git rev-parse --show-toplevel`/versions

sed -i "s/^NEO_MAJOR=.*/NEO_MAJOR=${neo_major}/" debian/rules
sed -i "s/^NEO_MINOR=.*/NEO_MINOR=${neo_minor}/" debian/rules
sed -i "s/^NEO_BUILD=.*/NEO_BUILD=${neo_build}/" debian/rules

sed -i "s/^ libigc-dev (>= .*/ libigc-dev (>= ${igc_ver}-1~),/" debian/control
sed -i "s/^ libigc (>= .*/ libigc (>= ${igc_ver}-1~),/" debian/control

./change_changelog

