#!/bin/bash
set -x

source `git rev-parse --show-toplevel`/versions

sed -i "s/^NEO_MAJOR=.*/NEO_MAJOR=${neo_major}/" debian/rules
sed -i "s/^NEO_MINOR=.*/NEO_MINOR=${neo_minor}/" debian/rules
sed -i "s/^NEO_BUILD=.*/NEO_BUILD=${neo_build}/" debian/rules

./change_changelog

