#!/bin/bash

. ./version

wget --no-check-certificate https://github.com/llvm/llvm-project/archive/${llvm_commit}/intel-graphics-compiler_${VER}.orig-llvm-project.tar.gz
wget --no-check-certificate https://github.com/intel/opencl-clang/archive/${opencl_clang_commit}/intel-graphics-compiler_${VER}.orig-opencl-clang.tar.gz
wget --no-check-certificate https://github.com/KhronosGroup/SPIRV-LLVM-Translator/archive/${spirv_llvm_translator_commit}/intel-graphics-compiler_${VER}.orig-llvm-spirv.tar.gz
wget --no-check-certificate https://github.com/intel/llvm-patches/archive/${llvm_patches_commit}/intel-graphics-compiler_${VER}.orig-llvm-patches.tar.gz
wget --no-check-certificate https://github.com/intel/intel-graphics-compiler/archive/${igc_commit}/intel-graphics-compiler_${VER}.orig-igc.tar.gz

