#!/bin/bash
set -x

source `git rev-parse --show-toplevel`/versions

release=$(awk -F '=' '/^IGC_PACKAGE_RELEASE/ {print $2}' debian/rules)
echo "current igc: ${release}"

new_build=$(echo ${igc_ver} | awk -F '.' '{print $3}')
echo "new build: ${new_build}"


sed -i "s/^IGC_PACKAGE_RELEASE=${release}/IGC_PACKAGE_RELEASE=${new_build}/" debian/rules

