#!/bin/bash
source ../../versions

wget https://github.com/intel/compute-runtime/releases/download/${neo_ver}/intel-gmmlib_${gmm_ver}_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/${neo_ver}/intel-igc-core_${igc_ver}_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/${neo_ver}/intel-igc-opencl_${igc_ver}_amd64.deb
wget https://github.com/intel/compute-runtime/releases/download/${neo_ver}/intel-opencl_${neo_ver}_amd64.deb

