#!/bin/bash

. ../versions

if [ ! -d src ]; then mkdir src ; fi

rm -rf llvm-spirv spirv-llvm-translator.tar.gz src/spirv-llvm-translator.tar.gz
git clone https://github.com/KhronosGroup/SPIRV-LLVM-Translator.git llvm-spirv
cd llvm-spirv
git checkout -b build ${spirv_llvm_translator_commit}
cd ..
tar czf src/spirv-llvm-translator.tar.gz llvm-spirv


