#!/bin/bash
set -x

source `git rev-parse --show-toplevel`/versions
GITUSER=`git config --get user.name`
EMAIL=`git config --get user.email`

rpmdev-bumpspec --new "${gmm_ver}" --comment="Update to ${gmm_ver}" --userstring="${GITUSER} <${EMAIL}>" intel-gmmlib.spec
