#!/bin/bash

set -x

for dist in 7 8 stream
do
    pushd centos/$dist
    ./update-igc-spec
    popd
done

for dist in 33 34
do
    pushd fedora/$dist
    ./update-igc-spec
    popd
done

for dist in mageia/8
do
    pushd $dist
    ./update-igc-spec
    popd
done

for dist in 15.2 tumbleweed
do
    pushd opensuse/$dist
    ./update-igc-spec
    popd
done
