#!/bin/bash
source builds
source ../../versions

wget https://copr-be.cloud.fedoraproject.org/results/jdanecki/intel-opencl/fedora-32-x86_64/${gmm_build}-intel-gmmlib/intel-gmmlib-${gmm_ver}-1.fc32.x86_64.rpm
wget https://copr-be.cloud.fedoraproject.org/results/jdanecki/intel-opencl/fedora-32-x86_64/${gmm_build}-intel-gmmlib/intel-gmmlib-devel-${gmm_ver}-1.fc32.x86_64.rpm

wget https://copr-be.cloud.fedoraproject.org/results/jdanecki/intel-opencl/fedora-32-x86_64/${igc_build}-intel-igc/intel-igc-core-${igc_ver}-2.fc32.x86_64.rpm
wget https://copr-be.cloud.fedoraproject.org/results/jdanecki/intel-opencl/fedora-32-x86_64/${igc_build}-intel-igc/intel-igc-opencl-${igc_ver}-2.fc32.x86_64.rpm
wget https://copr-be.cloud.fedoraproject.org/results/jdanecki/intel-opencl/fedora-32-x86_64/${igc_build}-intel-igc/intel-igc-opencl-devel-${igc_ver}-2.fc32.x86_64.rpm

#wget https://copr-be.cloud.fedoraproject.org/results/jdanecki/intel-opencl/fedora-32-x86_64/${opencl_clang_build}-intel-opencl-clang/intel-opencl-clang-${opencl_clang_ver}-1.fc32.x86_64.rpm
#wget https://copr-be.cloud.fedoraproject.org/results/jdanecki/intel-opencl/fedora-32-x86_64/${opencl_clang_build}-intel-opencl-clang/intel-opencl-clang-devel-${opencl_clang_ver}-1.fc32.x86_64.rpm

#wget https://download.copr.fedorainfracloud.org/results/jdanecki/intel-opencl/fedora-32-x86_64/${spirv_llvm_translator_build}-spirv-llvm-translator/spirv-llvm-translator-${spirv_llvm_translator_ver}-1.fc32.x86_64.rpm
#wget https://download.copr.fedorainfracloud.org/results/jdanecki/intel-opencl/fedora-32-x86_64/${spirv_llvm_translator_build}-spirv-llvm-translator/spirv-llvm-translator-devel-${spirv_llvm_translator_ver}-1.fc32.x86_64.rpm

wget https://copr-be.cloud.fedoraproject.org/results/jdanecki/intel-opencl/fedora-32-x86_64/${neo_build}-intel-opencl/intel-opencl-${neo_ver}-1.fc32.x86_64.rpm

wget https://download.copr.fedorainfracloud.org/results/jdanecki/intel-opencl/fedora-32-x86_64/${level_zero_build}-level-zero/level-zero-${level_zero_ver}-1.fc32.x86_64.rpm
wget https://download.copr.fedorainfracloud.org/results/jdanecki/intel-opencl/fedora-32-x86_64/${level_zero_build}-level-zero/level-zero-devel-${level_zero_ver}-1.fc32.x86_64.rpm
