#!/bin/bash
set -x

source `git rev-parse --show-toplevel`/versions
GITUSER=`git config --get user.name`
EMAIL=`git config --get user.email`

rpmdev-bumpspec --new "${opencl_clang9_ver}" --comment="Update to ${opencl_clang9_ver}" --userstring="${GITUSER} <${EMAIL}>" opencl-clang.spec

