#!/bin/bash
source ../../versions

rm -rf sf
mkdir sf

OS_full=ubuntu-20.04
OS=~ppa1~focal1

URL=https://downloads.sourceforge.net/project/intel-compute-runtime/${neo_ver}/${OS_full}

for p in libigdgmm11_${gmm_ver}-2 libigdgmm-dev_${gmm_ver}-2 \
    libigc-dev_${igc_ver}-2 libigc_${igc_ver}-2
do
    f=${p}${OS}_amd64.deb
    wget -O sf/$f ${URL}/$f
done
p=intel-opencl-icd_${neo_ver}-1
f=${p}~ppa1~focal3_amd64.deb
wget -O sf/$f ${URL}/$f


